## Introduction

We are going to be using [scikit learn](http://scikit-learn.org/stable/index.html)

<img src='files/resources/scikit-learn-logo-small.png' align='left'><h2>Machine Learning in Python</h2>

<br>
* Simple and efficient tools for data mining and data analysis
* Accessible to everybody, and reusable in various contexts
* Built on NumPy, SciPy, and matplotlib
* Open source, commercially usable - BSD license


In [3]:
import os 
import pandas as pd

In [4]:
data = pd.read_csv("data/fullDataset.tsv", sep="\t",header=0)


/home/csumb/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2902: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [5]:
data.head()

key                   query  \
0  215248    all star ticket 2015   
1   42799            mga top bows   
2   73041  cross document markers   
3  138766      wall cabinet white   
4  222660   2.5 jato cooling head   

                                               Title LeafCats  ItemID  \
0  6N/7D Disney World All Star Music~ All Inclusi...    29579   67884   
1  MGTC/TD/TF, MGA, Morris Minor Top Wing Bolts s...    34206   21331   
2  New Cross Vice Gel Ink Pen Gift Set & Document...   165631   36048   
3  White PAPER TOWEL ROLL HOLDER Cabinet Wall Mou...    20643   49003   
4  ENGINE COOLING HEAD TRAXXAS JATO TRX 2.5 NITRO...    34061   71436   

   X_unit_id     SCORE  label_relevanceGrade  label_relevanceBinary  \
0  793072069   -1:1:-1                     3                      0   
1  687419458      3::2                     5                      0   
2  687423583     3:3:3                     6                      1   
3  780091360  -1:-2:-2                     1                      0   
4  793073501     3:3:3                     6                      1   

     feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0  2676.618000          0  -9.020574  -5.221152  32.879559   0.000000   
1  2676.618000          0  -7.435843  -5.986507  24.565182   0.036317   
2  2676.618000          0  -8.030511  -4.509118  48.652847   0.000000   
3  1557.416626          1  -8.218757  -6.132952  45.209755   0.000000   
4  2676.618000          0  -8.599997  -5.317750  79.376099   0.805351   

   feature_7  feature_8  feature_9  feature_10  
0        241   -1000000        139 -100.000000  
1          0          0        208 -100.000000  
2          0          0        226 -100.000000  
3       1258   -1000000        158    1.670978  
4          0          0        150    2.538091

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 78500 entries, 0 to 78499
Data columns (total 19 columns):
key                      78500 non-null int64
query                    78500 non-null object
Title                    78494 non-null object
LeafCats                 78500 non-null object
ItemID                   78500 non-null int64
X_unit_id                78500 non-null object
SCORE                    78500 non-null object
label_relevanceGrade     78500 non-null int64
label_relevanceBinary    78500 non-null float64
feature_1                78500 non-null float64
feature_2                78500 non-null float64
feature_3                78500 non-null float64
feature_4                78500 non-null float64
feature_5                78500 non-null float64
feature_6                78500 non-null float64
feature_7                78500 non-null float64
feature_8                78500 non-null float64
feature_9                78500 non-null int64
feature_10               78499 non-null 

In [7]:
data.describe()

key        ItemID  label_relevanceGrade  \
count   78500.000000  7.850000e+04          78500.000000   
mean    98346.614064  4.869803e+04              5.254777   
std     70253.651231  2.890059e+06              1.334406   
min         1.000000  1.000000e+00              0.000000   
25%     39209.750000  1.908475e+04              5.000000   
50%     78577.500000  3.831350e+04              6.000000   
75%    157546.250000  5.765925e+04              6.000000   
max    234520.000000  8.097468e+08              6.000000   

       label_relevanceBinary     feature_1     feature_2     feature_3  \
count           78500.000000  78500.000000  78500.000000  78500.000000   
mean                0.713653   2821.519304      0.562437     -7.754530   
std                 8.446960    834.067146      0.497410      1.162798   
min                 0.000000  -1890.000000     -9.658937    -13.563713   
25%                 0.000000   2676.618000      0.000000     -8.285197   
50%                 1.000000   2676.618000      1.000000     -7.651813   
75%                 1.000000   3237.216614      1.000000     -7.390667   
max              2363.750000   5286.000000      1.000000     -2.726150   

          feature_4     feature_5     feature_6       feature_7  \
count  78500.000000  78500.000000  78500.000000    78500.000000   
mean      -4.280808     47.526718      0.439879    50746.223210   
std        0.772099     24.222248     18.439044   228258.768038   
min      -10.324562      0.000000      0.000000 -1000000.000000   
25%       -4.736623     30.806008      0.101174        0.000000   
50%       -4.327543     44.189650      0.365236      191.000000   
75%       -3.766841     60.076828      0.613038     4707.250000   
max       42.595760    273.239624   5166.000000  3339990.000000   

            feature_8     feature_9    feature_10  
count    78500.000000  78500.000000  78499.000000  
mean   -240684.450178    171.255248    -62.985598  
std     527649.016958     41.412263     48.710378  
min   -1000000.000000   -100.000000   -100.000000  
25%   -1000000.000000    144.000000   -100.000000  
50%          0.000000    172.000000   -100.000000  
75%      98130.000000    203.000000      0.620428  
max    1000000.000000    240.000000     10.940677

In [8]:
data = data.dropna()
data.describe()

key        ItemID  label_relevanceGrade  \
count   78493.000000  78493.000000          78493.000000   
mean    98353.149287  38385.733390              5.254774   
std     70253.061135  22259.156287              1.334363   
min         1.000000      1.000000              0.000000   
25%     39212.000000  19088.000000              5.000000   
50%     78584.000000  38316.000000              6.000000   
75%    157548.000000  57660.000000              6.000000   
max    234520.000000  77080.000000              6.000000   

       label_relevanceBinary     feature_1     feature_2     feature_3  \
count           78493.000000  78493.000000  78493.000000  78493.000000   
mean                0.683526   2821.567172      0.562598     -7.754471   
std                 0.465103    834.042432      0.496069      1.162636   
min                 0.000000  -1890.000000      0.000000    -13.563713   
25%                 0.000000   2676.618000      0.000000     -8.285108   
50%                 1.000000   2676.618000      1.000000     -7.651790   
75%                 1.000000   3237.285645      1.000000     -7.390667   
max                 1.000000   5286.000000      1.000000     -2.726150   

          feature_4     feature_5     feature_6       feature_7  \
count  78493.000000  78493.000000  78493.000000    78493.000000   
mean      -4.281164     47.528829      0.374066    50762.626642   
std        0.753205     24.222072      0.280593   228237.868119   
min      -10.324562      0.000000      0.000000        0.000000   
25%       -4.736623     30.808287      0.101141        0.000000   
50%       -4.327510     44.190533      0.365175      191.000000   
75%       -3.766839     60.078297      0.613038     4706.000000   
max       -1.106641    273.239624      1.000000  3339990.000000   

           feature_8     feature_9    feature_10  
count    78493.00000  78493.000000  78493.000000  
mean   -240647.46213    171.256023    -62.984023  
std     527631.90141     41.400772     48.710849  
min   -1000000.00000      0.000000   -100.000000  
25%   -1000000.00000    144.000000   -100.000000  
50%          0.00000    172.000000   -100.000000  
75%      98130.00000    203.000000      0.620932  
max    1000000.00000    240.000000     10.940677

In [9]:
from bokeh.charts import defaults, Bar, output_notebook, show
defaults.plot_width = 500
defaults.plot_height = 300
output_notebook(hide_banner=True)

We can see that low relevance results are under represented:

In [10]:
p = Bar(data, 'label_relevanceGrade',  values='label_relevanceGrade', agg='count', title="Distribution of Relevance Grade")
show(p)

For machine learning a lazy algorithm could predict grade 6 for everything.  Predicting the rarer class 0 or 1 has less payoff.  To 'encourage' our algorithm to more discriminating classification we can turn the 6-level relevance score into a binary target.  Now it does not pay to classify everything as relevant.

In [11]:
p = Bar(data, 'label_relevanceBinary',  values='label_relevanceBinary', agg='count', title="Distribution of Relevance Grade")
show(p)

Let's look at the relationship between this binary relevance target and the features.

In [12]:
!pip install seaborn

You are using pip version 8.0.2, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [13]:
# %matplotlib inline
# import seaborn as sns;
# sns.set(style="ticks", color_codes=True)
# sns.pairplot(data[["feature_1", "feature_2", "feature_3", "feature_4", "feature_5", "feature_6",
#                   "feature_7", "feature_8", "feature_9", "feature_10"]])

In [14]:
# boxplot feature_1 by relevance label
from bokeh.io import gridplot
from bokeh.charts import BoxPlot, output_file, show

defaults.plot_width = 400
defaults.plot_height = 300

def bplot(feature):
    return BoxPlot(data, values=feature, label="label_relevanceBinary", outliers=False)

p = gridplot ( [ 
        [ bplot("feature_1"), bplot("feature_2") ],
        [ bplot("feature_3"), bplot("feature_4") ],
        [ bplot("feature_5"), bplot("feature_6") ],
        [ bplot("feature_7"), bplot("feature_8") ],
        [ bplot("feature_9"), bplot("feature_10") ] ] ) 
show(p)

## Training / Test data

We also want to scale our features to have zero mean and unit standard deviation.  This avoids certain features dominating the machine learning objective function - something that can lead to poorly performing models.



In [336]:
from sklearn import preprocessing
from sklearn.externals import joblib

data_0 = data_sample.loc[(data.label_relevanceBinary == 0),]
data_1 = data_sample.loc[(data.label_relevanceBinary == 1),]

data_0 = data_0.sample(10000, replace=True)
data_1 = data_1.sample(10000, replace=True)

data_balanced = data_0.append(data_1)

y = data_balanced["label_relevanceBinary"].values

scaler = preprocessing.StandardScaler().fit(data_balanced.loc[:,"feature_1":"feature_10"])

# Serialize for later when we deploy the model
joblib.dump(scaler,'models/scaler.pkl')

X = scaler.transform(data_balanced.loc[:,"feature_1":"feature_10"])

features = data_balanced.loc[:,"feature_1":"feature_10"].columns

print(X.mean(axis=0))
print(X.std(axis=0))


[ -2.84217094e-16   7.95807864e-17  -2.17426077e-16   7.27595761e-16
   1.39266376e-16   5.11590770e-17   5.68434189e-18  -6.75015599e-17
   9.94759830e-18   8.52651283e-17]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


When machine learning we train on one data set and measure performance on another - this ensures that our performance metrics are representative of the actual performance of the model - this helps avoid overfitting.

In [337]:
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state=73)

print("X training : " + str(X_train.shape))
print("y training : " + str(y_train.shape))
print("X test     : " + str(X_test.shape))
print("y test     : " + str(y_test.shape))

type(y_train)

X training : (15000, 10)
y training : (15000,)
X test     : (5000, 10)
y test     : (5000,)


numpy.ndarray

## Naive Model

Model 01 - just predict everything to be relevant and check performance - this is our baseline.

We now need to define the metric we are going to use to evaluate and compare models.  There are many classification metrics - based on the cells in the confusion matrix - expand this.
 
|                  || *Predicted*  | *Class*   ||
|------------------||--------------------------|||
|                  ||     -    |    +    | Total |
|*True*   |   -     |   TN     |    FP   |  N    |
|*Classs* |   +     |   FN     |    TP   |  P    |
|         | Total   |   N*     |    P*   |       |


Now we can define metrics based on the contingency table:

| Name                      |   Definition  |   Synonyms                                  |
|---------------------------|---------------|---------------------------------------------|
| False Positive Rate       |   FP / N      | Type-I error, 1-Specificity                 |
| True Positive Rate        |   TP / P      | 1-Type II error, power, sensitivity, recall |
| Positive Predictive Value |   TP / P*     | Precision, 1-false discovery proportion     |
| Negative Predictive Value |   TN / N*     |                                             |


Visual for this at https://en.wikipedia.org/wiki/Precision_and_recall - be careful not to introduce confusion here.  For the course we could just optimise on F1?

Sometimes we talk about the accuracy of a model as:

$
accuracy = \frac{(TP + TN)}{( N + P )}
$


Generally we are interested in precision and recall.  

* Precision
    * The fraction of cases predicted to be positive that are actually positive
    * High precision is acheived by ensuring that all the predicted positive cases are actually positive
    * Quality
* Recall
    * The fraction of the positive cases predicted to be positive 
    * High recall is acheived by a model predicts as many of the positive cases as possible 
    * Quantity

We can also define classification metrics that compbine both precision and recall.  The F1-score is one such metric that computes the geometric mean of precision and recall - applying equal emphasis to precision as recall:

$
F_1 = 2 \times \frac{ precision . recall}{precision + recall} 
$

But we may choose to attach emphasis to recall:

$
F_2 = 5 \times \frac{ precision . recall}{ (4 . precision) + recall} 
$

Or we may choose to place higher emphasis on precision:

$
F_{0.5} = 1.25 \times \frac{ precision . recall}{( 0.25 . precision) + recall} 
$



In [338]:
y_pred_01 = [1] * y_test.shape[0]

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred_01))
print(classification_report(y_test, y_pred_01))
print(accuracy_score(y_test, y_pred_01))

[[   0 2483]
 [   0 2517]]
             precision    recall  f1-score   support

        0.0       0.00      0.00      0.00      2483
        1.0       0.50      1.00      0.67      2517

avg / total       0.25      0.50      0.34      5000

0.5034


We can see that recall is 100% - we predicted every value that was positive correctly - but precision is low - of those predicted to be positve only 68% were actually postive.  This yields and F1 score of 81%.  This is our baseline upon which we want to improve.

## Support Vector Machine

SVMs are rapidly becoming the default "go to" classification algorithm.  They are fast, scalable and relatively simple despite the scary name!

To fit an SVM, and in general when performing Machine Learning, we scale the data to have zero mean and unit standard deviation - this ensures that the algorithms do not over rely on features with large values.




In [179]:
from sklearn import svm

svc = svm.SVC(kernel='linear', C=0.01).fit(X_train, y_train)
#svc = svm.SVC(kernel='rbf',gamma=0.7, C=1.0).fit(X_train, y_train)
#svc = svm.SVC(kernel='poly', degree = 3, C=1.0).fit(X_train, y_train)
y_pred_02 = svc.predict(X_test)

In [180]:
print(confusion_matrix(y_test, y_pred_02))
print(classification_report(y_test, y_pred_02))
print(accuracy_score(y_test, y_pred_02))

[[94 27]
 [62 67]]
             precision    recall  f1-score   support

        0.0       0.60      0.78      0.68       121
        1.0       0.71      0.52      0.60       129

avg / total       0.66      0.64      0.64       250

0.644


## Logistic Regression





In [181]:
from sklearn import linear_model
lgr = linear_model.LogisticRegression(penalty='l1').fit(X_train, y_train)
y_pred_03 = lgr.predict(X_test)

In [182]:
print(confusion_matrix(y_test, y_pred_03))
print(classification_report(y_test, y_pred_03))
print(accuracy_score(y_test, y_pred_03))

[[91 30]
 [53 76]]
             precision    recall  f1-score   support

        0.0       0.63      0.75      0.69       121
        1.0       0.72      0.59      0.65       129

avg / total       0.68      0.67      0.67       250

0.668


In [183]:
print(lgr.coef_)

[[ 0.64717901  0.28743147 -0.05600921  0.10437602  0.25229265  0.18286513
   0.17697981 -0.11460174 -0.04616584 -0.11411133]]


## Decision Tree

In [184]:
from sklearn import tree

clf = tree.DecisionTreeClassifier(min_samples_leaf=5, max_depth = 4).fit(X_train, y_train)
y_pred_04 = clf.predict(X_test)

In [185]:
print(confusion_matrix(y_test, y_pred_04))
print(classification_report(y_test, y_pred_04))
print(accuracy_score(y_test, y_pred_04))

[[73 48]
 [34 95]]
             precision    recall  f1-score   support

        0.0       0.68      0.60      0.64       121
        1.0       0.66      0.74      0.70       129

avg / total       0.67      0.67      0.67       250

0.672


In [162]:
from sklearn.externals.six import StringIO
with open("tree.dot", "w") as f:
    f = tree.export_graphviz(clf, filled=True, out_file=f)

In [163]:
! dot -Tpdf tree.dot -o tree.pdf

## Random Forests

In [186]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=200).fit(X_train, y_train)
y_pred_05 = clf.predict(X_test)

In [187]:
print(confusion_matrix(y_test, y_pred_05))
print(classification_report(y_test, y_pred_05))
print(accuracy_score(y_test, y_pred_05))

[[104  17]
 [ 18 111]]
             precision    recall  f1-score   support

        0.0       0.85      0.86      0.86       121
        1.0       0.87      0.86      0.86       129

avg / total       0.86      0.86      0.86       250

0.86


## K-nearest neighbour

In [189]:
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier(n_neighbors=10).fit(X_train, y_train)
y_pred_06 = clf.predict(X_test)

In [205]:
print(confusion_matrix(y_test, y_pred_06))
print(classification_report(y_test, y_pred_06))
print(accuracy_score(y_test, y_pred_06))

[[84 37]
 [49 80]]
             precision    recall  f1-score   support

        0.0       0.63      0.69      0.66       121
        1.0       0.68      0.62      0.65       129

avg / total       0.66      0.66      0.66       250

0.656


## Naive Bayes

In [293]:
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB().fit(X_train, y_train)
y_pred_07 = clf.predict(X_test)

In [294]:
print(confusion_matrix(y_test, y_pred_07))
print(classification_report(y_test, y_pred_07))
print(accuracy_score(y_test, y_pred_07))

[[86 35]
 [60 69]]
             precision    recall  f1-score   support

        0.0       0.59      0.71      0.64       121
        1.0       0.66      0.53      0.59       129

avg / total       0.63      0.62      0.62       250

0.62


In [298]:
clf.theta_


array([[-0.32182856, -0.15007347, -0.00373028, -0.16356497, -0.1141782 ,
        -0.25727614, -0.05660024,  0.06212886,  0.02489654, -0.02444751],
       [ 0.30598803,  0.16278547, -0.02914801,  0.15160933,  0.11741225,
         0.225499  ,  0.01489977, -0.1334623 , -0.04661067,  0.02064945]])

## Gradient Tree Boosting 

In [339]:
from sklearn.ensemble import GradientBoostingClassifier

clf = GradientBoostingClassifier(n_estimators=13, learning_rate=1.0, max_depth=10).fit(X_train, y_train)
y_pred_08 = clf.predict(X_test)

In [340]:
print(confusion_matrix(y_test, y_pred_08))
print(classification_report(y_test, y_pred_08))
print(accuracy_score(y_test, y_pred_08))

[[2483    0]
 [   0 2517]]
             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00      2483
        1.0       1.00      1.00      1.00      2517

avg / total       1.00      1.00      1.00      5000

1.0


In [341]:
test_score = []
for i, p in enumerate(clf.staged_predict(X_test)):
    #print(i, clf.loss_(y_test, p))
    test_score.append(clf.loss_(y_test, p))


df = pd.DataFrame({ 'n' : range(len(test_score)), 'train' : clf.train_score_, 'test' : test_score})

from bokeh.charts import Line

line = Line(data=df, x='n', y=['test'])
show(line)

In [342]:
from bokeh.charts import Bar
from bokeh.charts.attributes import CatAttr

df = pd.DataFrame({ 'importance' : clf.feature_importances_, 'feature' : features})
df.sort_values(by='importance', inplace=True, ascending=False)

bar = Bar(df, label=CatAttr(columns=['feature'], sort=False), values='importance'  )
show(bar)

In [343]:
# Save clasifier for deployment in our search engine
from sklearn.externals import joblib
joblib.dump(clf,'models/mlr.pkl')

['models/mlr.pkl',
 'models/mlr.pkl_01.npy',
 'models/mlr.pkl_02.npy',
 'models/mlr.pkl_03.npy']